import React from "react"
import QuizModel from "../../components/Quizmodel"
import { Box, Text, Button } from "@chakra-ui/react"
import Navbar from "../../components/Navbar"
import Link from "next/link"

const quizdata = [
  {
    id: 1,
    question:
      "Q1. what type of tuple machine is also called as Finite state Machine?",
    options: ["4", "5", "6", "None of the above"],
  },
  {
    id: 2,
    question: "Q2. Number of states required to accept strings ends with 101.",
    options: ["3", "2", " 4", "can't be represented"],
  },
  {
    id: 3,
    question: "Q3. Language of Finite automata is generated by:",
    options: [
      "Type 0 grammar",
      "Type 1 grammar",
      "Type 2 grammar",
      "Type 3 grammar",
    ],
  },
  {
    id: 4,
    question: "Q4. Finite automata needs number of stacks = ",
    options: ["0", "5", "2", "None of the above."],
  },
  {
    id: 5,
    question:
      "Q5. Which of the following are the examples of infinite state machine system? ",
    options: [
      "Control Mechanism of an elevator",
      "combinational logic",
      "Digital Watches",
      "Both a & b",
    ],
  },
]

function quiz() {
  return (
    <>
      <Navbar />
      <Box border="1px solid" mx="200px" my="80px">
        <Text fontSize="36px" fontWeight="bold" textAlign="center">
          Welcome to FLAT quiz
        </Text>
        <Box>
          {quizdata.map((demo) => (
            <QuizModel question={demo.question} options={demo.options} />
          ))}
        </Box>
        <Box mx="450px" my="80px">
          <Link href="/thankyou">
            <Button
              minW="200px"
              mt="25px"
              h="36px"
              backgroundColor="#6C63FF"
              color="#000000"
              borderRadius="5px"
              fontSize="15px"
              fontWeight="bold"
            >
              Submit
            </Button>
          </Link>
        </Box>
      </Box>
    </>
  )
}

export default quiz
